export const ERROR_CODES = {
  // Errores generales de validación
  REQUIRED_FIELD: "REQUIRED_FIELD",
  INVALID_NUMBER: "INVALID_NUMBER",
  INVALID_AMOUNT: "INVALID_AMOUNT",
  INVALID_DATE: "INVALID_DATE",
  INVALID_TEXT: "INVALID_TEXT",
  INVALID_OPTION: "INVALID_OPTION",

  // Errores relacionados con registros
  RECORD_NOT_FOUND: "RECORD_NOT_FOUND",
  DUPLICATE_RECORD: "DUPLICATE_RECORD",
  DELETE_NOT_ALLOWED: "DELETE_NOT_ALLOWED",

  // Errores relacionados con movimientos
  INVALID_MOVEMENT_TYPE: "INVALID_MOVEMENT_TYPE",
  PROJECT_REQUIRED: "PROJECT_REQUIRED",
  CATEGORY_REQUIRED: "CATEGORY_REQUIRED",
  LIMIT_EXCEEDED: "LIMIT_EXCEEDED",

  // Errores de almacenamiento temporal
  STORAGE_READ_ERROR: "STORAGE_READ_ERROR",
  STORAGE_WRITE_ERROR: "STORAGE_WRITE_ERROR",
  INVALID_STORED_DATA: "INVALID_STORED_DATA",

  // Error desconocido
  UNKNOWN_ERROR: "UNKNOWN_ERROR",
};